#!/usr/bin/make
WGET=wget --continue --no-verbose --show-progress --directory-prefix=cache/downloads/

all: download_extra

clean:
	rm -rvf config/packages.chroot/
	rm -rvf cache/downloads
	rm -rf config/includes.chroot/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}
	rm -rf config/includes.chroot/usr/lib/thunderbird/extensions/gconversation@xulforum.org.xpi

clean_all: clean
	rm -rvf cache/downloads/


download_extra: clean
	# Download additional software from third-party repository (https://nodiscc.gitlab.io/toolbox)
	mkdir -p cache/downloads/ config/packages.chroot/

	# EXTRA https://github.com/az0/cleanerml
	$(WGET) https://nodiscc.gitlab.io/toolbox/pool/main/b/bleachbit-cleanerml/bleachbit-cleanerml_0.0.1~git0+5bc2961_all.deb
	cp cache/downloads/bleachbit-cleanerml_0.0.1~git0+5bc2961_all.deb config/packages.chroot/

	# EXTRA https://github.com/nodiscc/user.js
	$(WGET) https://nodiscc.gitlab.io/toolbox/pool/main/u/user.js/user.js_0.13.0-1_all.deb
	cp cache/downloads/user.js_0.13.0-1_all.deb config/packages.chroot/

	# EXTRA https://addons.thunderbird.net/thunderbird/addon/gmail-conversation-view/
	mkdir -p config/includes.chroot/usr/lib/thunderbird/extensions/
	$(WGET) https://addons.thunderbird.net/thunderbird/downloads/latest/gmail-conversation-view/addon-54035-latest.xpi -O config/includes.chroot/usr/lib/thunderbird/extensions/gconversation@xulforum.org.xpi
