# this workflow will not work in containers, only on VMs/bare-metal hosts sue to limitation of
# container-based environments (filesystems mounted with nodev/noexec). Since parts of the build
# process require root access/the following should be configured in /etc/sudoers.d/debian-live-config:
# act-runner ALL=NOPASSWD: /usr/bin/apt -y install live-build make build-essential wget git unzip colordiff apt-transport-https rename ovmf rsync python3-venv gnupg
# act-runner ALL=NOPASSWD: /usr/bin/lb
# act-runner ALL=NOPASSWD: /usr/bin/lb
# act-runner ALL=NOPASSWD: /usr/bin/lb

name: CI
on:
  push:

concurrency:
  group: ${{ gitea.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: host
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: run build
      run: make
    - name: compute and sign checksums
      run: make checksums
    - name: cache downloaded packages
      uses: actions/cache@v3
      with:
        path: |
          cache/downloads/
          cache/packages.bootstrap/
          cache/packages.chroot/
          cache/packages.installer_debian-installer.udeb/
      key: packages-cache
    - name: debug
      run: ls -l; git st --untracked-files
    # files generated by the build process must be explicitely cleaned, else the builtin post-build action will not be able to remove files ownerd by root created by sudo lb build
    - name: clean build artifacts
      if: always()
      run: make clean
