--output '%(uploader)s - %(title)s - %(extractor)s-%(id)s.%(ext)s'
--trim-filenames 180
--write-info-json
--write-subs
--write-auto-subs
--convert-subs 'srt'
--sub-langs 'en,fr'
--embed-chapters
--restrict-filenames
--compat-options no-live-chat
#--add-metadata
